# Generated by Django 3.0.5 on 2020-05-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('blinds', models.CharField(choices=[('1-2', '1-2'), ('2-4', '2-4'), ('5-10', '5-10')], max_length=10)),
                ('max_players', models.CharField(choices=[('2', 'Heads Up'), ('6', '6 Max'), ('9', '9 Max')], max_length=1)),
                ('game_type', models.CharField(choices=[('NL', 'No Limit Holdem'), ('PLO', 'Pot Limit Omaha')], max_length=3)),
            ],
            options={
                'ordering': ['game_type', 'blinds'],
            },
        ),
    ]
